import static com.kazurayam.junit4ks.JUnitCustomKeywords.runWithJUnitRunner

import com.kazurayam.ks.globalvariable.LookatGlobalVariablesKeywordTest

runWithJUnitRunner(LookatGlobalVariablesKeywordTest.class)
