import static com.kazurayam.junit4ks.JUnitCustomKeywords.runWithJUnitRunner

import com.kazurayam.ks.globalvariable.LookAtGlobalVariablesKeywordTest

runWithJUnitRunner(LookAtGlobalVariablesKeywordTest.class)
