import static com.kazurayam.junit4ks.JUnitCustomKeywords.runWithJUnitRunner

import com.kazurayam.ks.globalvariable.GlobalVariableProfilePairTest

runWithJUnitRunner(GlobalVariableProfilePairTest.class)

