import com.kazurayam.ks.ExecutionProfilesLoader

/**
 * Test Cases/loadExecutionProfile
 */
ExecutionProfilesLoader loader = new ExecutionProfilesLoader()

//loader.loadProfiles('main_Base', 'main_envDevelopment', 'main_category0', 'main_includeSheets_ALL', 'main_includeURLs_ALL')
//loader.loadProfiles('main_Base', 'main_envDevelopment', 'main_category0', 'main_includeSheets_ALL', 'main_includeURLs_login')
//loader.loadProfiles('main_Base', 'main_envDevelopment', 'main_category0', 'main_includeSheets_ALL', 'main_includeURLs_top')
//loader.loadProfiles('main_Base', 'main_envDevelopment', 'main_category0', 'main_includeSheets_CompanyA', 'main_includeURLs')


//loader.loadProfiles('main_Base', 'main_envDevelopment', 'main_category0', 'main_includeSheets_CompanyB')
//loader.loadProfiles('main_Base', 'main_envDevelopment', 'main_category0', 'main_includeSheets_CompanyC')
//loader.loadProfiles('main_Base', 'main_envDevelopment', 'main_category0', 'main_includeSheets_GroupG')
//loader.loadProfiles('main_Base', 'main_envDevelopment', 'main_category1', 'main_includeSheets_ALL')
//loader.loadProfiles('main_Base', 'main_envDevelopment', 'main_category1', 'main_includeSheets_CompanyA')
//loader.loadProfiles('main_Base', 'main_envDevelopment', 'main_category1', 'main_includeSheets_CompanyB')
//loader.loadProfiles('main_Base', 'main_envDevelopment', 'main_category1', 'main_includeSheets_CompanyC')
//loader.loadProfiles('main_Base', 'main_envDevelopment', 'main_category1', 'main_includeSheets_GroupG')
//loader.loadProfiles('main_Base', 'main_envDevelopment', 'main_category2', 'main_includeSheets_ALL')
//loader.loadProfiles('main_Base', 'main_envDevelopment', 'main_category2', 'main_includeSheets_CompanyA')
//loader.loadProfiles('main_Base', 'main_envDevelopment', 'main_category2', 'main_includeSheets_CompanyB')
//loader.loadProfiles('main_Base', 'main_envDevelopment', 'main_category2', 'main_includeSheets_CompanyC')
//loader.loadProfiles('main_Base', 'main_envDevelopment', 'main_category2', 'main_includeSheets_GroupG')
//loader.loadProfiles('main_Base', 'main_envDevelopment', 'main_category3', 'main_includeSheets_ALL')
//loader.loadProfiles('main_Base', 'main_envDevelopment', 'main_category3', 'main_includeSheets_CompanyA')
//loader.loadProfiles('main_Base', 'main_envDevelopment', 'main_category3', 'main_includeSheets_CompanyB')
//loader.loadProfiles('main_Base', 'main_envDevelopment', 'main_category3', 'main_includeSheets_CompanyC')
//loader.loadProfiles('main_Base', 'main_envDevelopment', 'main_category3', 'main_includeSheets_GroupG')
//loader.loadProfiles('main_Base', 'main_envProduction', 'main_category0', 'main_includeSheets_ALL')
//loader.loadProfiles('main_Base', 'main_envProduction', 'main_category0', 'main_includeSheets_CompanyA')
//loader.loadProfiles('main_Base', 'main_envProduction', 'main_category0', 'main_includeSheets_CompanyB')
//loader.loadProfiles('main_Base', 'main_envProduction', 'main_category0', 'main_includeSheets_CompanyC')
//loader.loadProfiles('main_Base', 'main_envProduction', 'main_category0', 'main_includeSheets_GroupG')
//loader.loadProfiles('main_Base', 'main_envProduction', 'main_category1', 'main_includeSheets_ALL')
//loader.loadProfiles('main_Base', 'main_envProduction', 'main_category1', 'main_includeSheets_CompanyA')
//loader.loadProfiles('main_Base', 'main_envProduction', 'main_category1', 'main_includeSheets_CompanyB')
//loader.loadProfiles('main_Base', 'main_envProduction', 'main_category1', 'main_includeSheets_CompanyC')
//loader.loadProfiles('main_Base', 'main_envProduction', 'main_category1', 'main_includeSheets_GroupG')
//loader.loadProfiles('main_Base', 'main_envProduction', 'main_category2', 'main_includeSheets_ALL')
//loader.loadProfiles('main_Base', 'main_envProduction', 'main_category2', 'main_includeSheets_CompanyA')
//loader.loadProfiles('main_Base', 'main_envProduction', 'main_category2', 'main_includeSheets_CompanyB')
//loader.loadProfiles('main_Base', 'main_envProduction', 'main_category2', 'main_includeSheets_CompanyC')
//loader.loadProfiles('main_Base', 'main_envProduction', 'main_category2', 'main_includeSheets_GroupG')
//loader.loadProfiles('main_Base', 'main_envProduction', 'main_category3', 'main_includeSheets_ALL')
//loader.loadProfiles('main_Base', 'main_envProduction', 'main_category3', 'main_includeSheets_CompanyA')
//loader.loadProfiles('main_Base', 'main_envProduction', 'main_category3', 'main_includeSheets_CompanyB')
//loader.loadProfiles('main_Base', 'main_envProduction', 'main_category3', 'main_includeSheets_CompanyC')
//loader.loadProfiles('main_Base', 'main_envProduction', 'main_category3', 'main_includeSheets_GroupG')
//loader.loadProfiles('main_Base', 'main_envStaging', 'main_category0', 'main_includeSheets_ALL')
//loader.loadProfiles('main_Base', 'main_envStaging', 'main_category0', 'main_includeSheets_CompanyA')
//loader.loadProfiles('main_Base', 'main_envStaging', 'main_category0', 'main_includeSheets_CompanyB')
//loader.loadProfiles('main_Base', 'main_envStaging', 'main_category0', 'main_includeSheets_CompanyC')
//loader.loadProfiles('main_Base', 'main_envStaging', 'main_category0', 'main_includeSheets_GroupG')
//loader.loadProfiles('main_Base', 'main_envStaging', 'main_category1', 'main_includeSheets_ALL')
//loader.loadProfiles('main_Base', 'main_envStaging', 'main_category1', 'main_includeSheets_CompanyA')
//loader.loadProfiles('main_Base', 'main_envStaging', 'main_category1', 'main_includeSheets_CompanyB')
//loader.loadProfiles('main_Base', 'main_envStaging', 'main_category1', 'main_includeSheets_CompanyC')
//loader.loadProfiles('main_Base', 'main_envStaging', 'main_category1', 'main_includeSheets_GroupG')
//loader.loadProfiles('main_Base', 'main_envStaging', 'main_category2', 'main_includeSheets_ALL')
//loader.loadProfiles('main_Base', 'main_envStaging', 'main_category2', 'main_includeSheets_CompanyA')
//loader.loadProfiles('main_Base', 'main_envStaging', 'main_category2', 'main_includeSheets_CompanyB')
//loader.loadProfiles('main_Base', 'main_envStaging', 'main_category2', 'main_includeSheets_CompanyC')
//loader.loadProfiles('main_Base', 'main_envStaging', 'main_category2', 'main_includeSheets_GroupG')
//loader.loadProfiles('main_Base', 'main_envStaging', 'main_category3', 'main_includeSheets_ALL')
//loader.loadProfiles('main_Base', 'main_envStaging', 'main_category3', 'main_includeSheets_CompanyA')
//loader.loadProfiles('main_Base', 'main_envStaging', 'main_category3', 'main_includeSheets_CompanyB')
//loader.loadProfiles('main_Base', 'main_envStaging', 'main_category3', 'main_includeSheets_CompanyC')
//loader.loadProfiles('main_Base', 'main_envStaging', 'main_category3', 'main_includeSheets_GroupG'